apiVersion: v1
kind: ConfigMap
metadata:
  name: devspaces-git-config
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-configmap: "true"
  annotations:
    controller.devfile.io/mount-path: "/home/user/.gitconfig.d"
data:
  gitconfig: |
    [user]
      name = agapebondservant
      email = agapebondservant@email.com
